---
- name: Ensure pip_install_packages are installed.
  pip:
    name: "{{ item.name | default(item) }}"
    version: "{{ item.version | default(omit) }}"
    virtualenv: "{{ item.virtualenv | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
  with_items: "{{ pip_install_packages }}"

- name: install docker-py
  become: yes
  pip:
    name: docker-py
    state: present
