---
- name: Creates directory
  become: yes
  file: 
    path: /opt/docker/jenkins/jenkins_home 
    state: directory
    owner: 1000
    group: 1000
    mode: 0755

- name: install docker-py
  become: yes
  pip:
    name: docker-py
    state: present

- name: Jenkins Docker Image
  become: yes
  docker_container:
    name: jenkins
    image: "jenkins/jenkins:lts"
    state: present

- name: Starting Container
  become: yes
  docker_container:
    name: jenkins
    image: "jenkins/jenkins:lts"
    state: started
    restart_policy: unless-stopped
    restart: yes
    ports:
    - "80:8080"
    - "50000:50000"
    volumes:
    - "/opt/docker/jenkins/jenkins_home:/var/jenkins_home"
