---
- name: Creates directory
  become: yes
  file:
   path: /opt/docker/nexus/nexus-data
   state: directory
   owner: 200
   group: 200
   mode: 0755

- name: install docker-py
  become: yes
  pip:
    name: docker-py
    state: present

- name: Nexus docker image
  become: yes
  docker_container:
    name: nexus
    image: sonatype/nexus3
    state: present

- name: Start a container
  become: yes
  docker_container:
    name: nexus
    image: sonatype/nexus3
    state: started
    restart_policy: unless-stopped
    ports:
     - "8081:8081"
    volumes:
     - "/opt/docker/nexus/nexus-data:/nexus-data"
